export const chats = [
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
    { user: 'User A', content: 'Chat Content ...', date: new Date() },
    { user: 'User B', content: 'Chat Content ...', date: new Date() },
]